<?php

namespace ContainerYRiTrul;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFunctionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FunctionController' shared autowired service.
     *
     * @return \App\Controller\FunctionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FunctionController'] = $instance = new \App\Controller\FunctionController(($container->privates['App\\Repository\\NewletterRepository'] ?? $container->load('getNewletterRepositoryService')), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.8FV7jiY'] ?? $container->load('get_ServiceLocator_8FV7jiYService'))->withContext('App\\Controller\\FunctionController', $container));

        return $instance;
    }
}
