<?php

namespace ContainerYRiTrul;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MotoRepository' shared autowired service.
     *
     * @return \App\Repository\MotoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MotoRepository'] = new \App\Repository\MotoRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
