<?php

namespace ContainerYRiTrul;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewletterRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\NewletterRepository' shared autowired service.
     *
     * @return \App\Repository\NewletterRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Repository\\NewletterRepository'])) {
            return $container->privates['App\\Repository\\NewletterRepository'];
        }

        return $container->privates['App\\Repository\\NewletterRepository'] = new \App\Repository\NewletterRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)), $a);
    }
}
