<?php

namespace ContainerNMNnWSX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControlleroccasionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.00epxik.App\Controller\PageController::occasion()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.00epxik.App\\Controller\\PageController::occasion()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'MarquesRepository' => ['privates', 'App\\Repository\\MarqueRepository', 'getMarqueRepositoryService', true],
            'motoRepository' => ['privates', 'App\\Repository\\MotoRepository', 'getMotoRepositoryService', true],
        ], [
            'MarquesRepository' => 'App\\Repository\\MarqueRepository',
            'motoRepository' => 'App\\Repository\\MotoRepository',
        ]))->withContext('App\\Controller\\PageController::occasion()', $container);
    }
}
