<?php

namespace ContainerWZ5p4wr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WSbp0fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wSbp0f_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wSbp0f_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\FunctionController::motosParMarque' => ['privates', '.service_locator.hznGe2U.App\\Controller\\FunctionController::motosParMarque()', 'getFunctionControllermotosParMarqueService', true],
            'App\\Controller\\PageController::catalogue' => ['privates', '.service_locator.MEncpnc.App\\Controller\\PageController::catalogue()', 'getPageControllercatalogueService', true],
            'App\\Controller\\PageController::occasion' => ['privates', '.service_locator.00epxik.App\\Controller\\PageController::occasion()', 'getPageControlleroccasionService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Controller\\FunctionController:motosParMarque' => ['privates', '.service_locator.hznGe2U.App\\Controller\\FunctionController::motosParMarque()', 'getFunctionControllermotosParMarqueService', true],
            'App\\Controller\\PageController:catalogue' => ['privates', '.service_locator.MEncpnc.App\\Controller\\PageController::catalogue()', 'getPageControllercatalogueService', true],
            'App\\Controller\\PageController:occasion' => ['privates', '.service_locator.00epxik.App\\Controller\\PageController::occasion()', 'getPageControlleroccasionService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
        ], [
            'App\\Controller\\FunctionController::motosParMarque' => '?',
            'App\\Controller\\PageController::catalogue' => '?',
            'App\\Controller\\PageController::occasion' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FunctionController:motosParMarque' => '?',
            'App\\Controller\\PageController:catalogue' => '?',
            'App\\Controller\\PageController:occasion' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
