<?php

namespace ContainerWZ5p4wr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFunctionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FunctionController' shared autowired service.
     *
     * @return \App\Controller\FunctionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FunctionController.php';

        $container->services['App\\Controller\\FunctionController'] = $instance = new \App\Controller\FunctionController(($container->privates['App\\Repository\\NewletterRepository'] ?? $container->load('getNewletterRepositoryService')), ($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.8FV7jiY'] ?? $container->load('get_ServiceLocator_8FV7jiYService'))->withContext('App\\Controller\\FunctionController', $container));

        return $instance;
    }
}
