<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYRiTrul\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYRiTrul/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYRiTrul.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYRiTrul\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYRiTrul\App_KernelProdContainer([
    'container.build_hash' => 'YRiTrul',
    'container.build_id' => '696cf74d',
    'container.build_time' => 1717750483,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYRiTrul');
