<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'add_email' => [[], ['_controller' => 'App\\Controller\\FunctionController::addEmail'], [], [['text', '/add-email']], [], [], []],
    'motos_par_marque' => [[], ['_controller' => 'App\\Controller\\FunctionController::motosParMarque'], [], [['text', '/select_m']], [], [], []],
    'motos_all' => [[], ['_controller' => 'App\\Controller\\FunctionController::motosAll'], [], [['text', '/select_a']], [], [], []],
    'app_accueil' => [[], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '/']], [], [], []],
    'catalogue' => [[], ['_controller' => 'App\\Controller\\PageController::catalogue'], [], [['text', '/catalogue']], [], [], []],
    'app_occasion' => [[], ['_controller' => 'App\\Controller\\PageController::occasion'], [], [['text', '/occasion']], [], [], []],
    'app_detail_occasion' => [['moto_id'], ['_controller' => 'App\\Controller\\PageController::detail_occasion'], [], [['variable', '/', '[^/]++', 'moto_id', true], ['text', '/occasion']], [], [], []],
    'App\Controller\FunctionController::addEmail' => [[], ['_controller' => 'App\\Controller\\FunctionController::addEmail'], [], [['text', '/add-email']], [], [], []],
    'App\Controller\FunctionController::motosParMarque' => [[], ['_controller' => 'App\\Controller\\FunctionController::motosParMarque'], [], [['text', '/select_m']], [], [], []],
    'App\Controller\FunctionController::motosAll' => [[], ['_controller' => 'App\\Controller\\FunctionController::motosAll'], [], [['text', '/select_a']], [], [], []],
    'App\Controller\PageController::index' => [[], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\PageController::catalogue' => [[], ['_controller' => 'App\\Controller\\PageController::catalogue'], [], [['text', '/catalogue']], [], [], []],
    'App\Controller\PageController::occasion' => [[], ['_controller' => 'App\\Controller\\PageController::occasion'], [], [['text', '/occasion']], [], [], []],
    'App\Controller\PageController::detail_occasion' => [['moto_id'], ['_controller' => 'App\\Controller\\PageController::detail_occasion'], [], [['variable', '/', '[^/]++', 'moto_id', true], ['text', '/occasion']], [], [], []],
];
