<?php

namespace ContainerSYgQyzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFunctionControllermotosAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hznGe2U.App\Controller\FunctionController::motosAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hznGe2U.App\\Controller\\FunctionController::motosAll()'] = ($container->privates['.service_locator.hznGe2U'] ?? $container->load('get_ServiceLocator_HznGe2UService'))->withContext('App\\Controller\\FunctionController::motosAll()', $container);
    }
}
