import os
import requests
from PIL import Image
from io import BytesIO

# Dictionnaire des marques et de leurs sites web
brands_sites = {
    "ACCESS": "access.com",
    "AEON": "aeon.com",
    "AERMACCHI": "aermacchi.com",
    "APRILIA": "aprilia.com",
    "ARCTIC CAT": "arcticcat.com",
    "ARIIC": "ariic.com",
    "ASKOLL": "askoll.com",
    "AVERSUS": "aversus.com",
    "BENELLI": "benelli.com",
    "BETA": "betamotor.com",
    "BIMOTA": "bimota.com",
    "BMW": "bmw.com",
    "BOOM-TRIKES": "boom-trikes.com",
    "BRIXTON": "brixton-motorcycles.com",
    "BSA": "bsacompany.com",
    "BUELL": "buell.com",
    "BULLIT": "bullitmotorcycles.com",
    "BYE BIKE": "byebike.com",
    "CAGIVA": "cagiva.it",
    "CAN-AM": "can-am.brp.com",
    "CF MOTO": "cfmoto.com",
    "CITO": "cito.com",
    "COLOVE": "colove.com",
    "CONDOR": "condorcycles.com",
    "CORVUS": "corvus.com",
    "DAELIM": "daelim.co.kr",
    "DAXARA": "daxara.com",
    "DERBI": "derbi.com",
    "DKW": "dkw.com",
    "DUCATI": "ducati.com",
    "E.F.O": "efo.com",
    "EASYCOOL": "easycool.com",
    "ECCITY": "eccity-motocycles.com",
    "ECOOTER": "ecooter.com",
    "E-Fati": "e-fati.com",
    "EFUN": "efun.com",
    "EGLI": "egli.com",
    "ELECTRIC MOTION": "electric-motion.fr",
    "EML": "emltrikes.nl",
    "ENERGICA": "energica.com",
    "E-SCOOTER": "e-scooter.com",
    "ETRIX": "etrix.com",
    "EXPLORER": "explorer.de",
    "FANTIC": "fantic.com",
    "GARELLI": "garelli.com",
    "GASGAS": "gasgas.com",
    "GILERA": "gilera.com",
    "GRAF CARELLO": "grafcarello.com",
    "HARLEY-DAVIDSON": "harley-davidson.com",
    "HONDA": "honda.com",
    "HOREX": "horex.com",
    "HPU": "hpu.com",
    "HUSABERG": "husaberg.com",
    "HUSQVARNA": "husqvarna-motorcycles.com",
    "HUSQVARNA BICYCLES": "husqvarna-bicycles.com",
    "HVR": "hvr.com",
    "HYOSUNG": "hyosungmotors.com",
    "HYTRACK": "hytrack.com",
    "INDIAN": "indianmotorcycle.com",
    "INTENSE": "intensecycles.com",
    "ITALJET": "italjet.com",
    "JAWA": "jawa.eu",
    "KAWASAKI": "kawasaki.com",
    "KITO": "kitomotor.com",
    "KL": "kl.com",
    "KOVE": "kovemoto.com",
    "KRÄMER": "kraemer-motorcycles.com",
    "KTM": "ktm.com",
    "KUMPAN": "kumpan-electric.com",
    "KYBURZ": "kyburz-switzerland.ch",
    "KYMCO": "kymco.com",
    "LAMBRETTA": "lambretta.com",
    "LAVERDA": "laverda.com",
    "LML": "lmlit.com",
    "LVNENG": "lvneng.com",
    "LYNX": "lynx.com",
    "MALAGUTI": "malaguti.com",
    "MANGOSTEEN": "mangosteen.com",
    "MASH": "mashmotors.fr",
    "MATCHLESS": "matchlesslondon.com",
    "MBK": "mbk.com",
    "MIDLAND CHOPPERS": "midlandchoppers.com",
    "MONDIAL": "mondialmoto.it",
    "MONNIER-HONDA": "monnier-honda.com",
    "MONTESA": "montesa.com",
    "MOTO GUZZI": "motoguzzi.com",
    "MOTO MORINI": "motomorini.com",
    "MOTOBI": "motobi.com",
    "MOTRON": "motron-motorcycles.com",
    "MV AGUSTA": "mvagusta.com",
    "NEXT": "nextmotorcycle.com",
    "NIU": "niu.com",
    "NORTON": "nortonmotorcycles.com",
    "NSU": "nsu.com",
    "ODES": "odes.com",
    "ONLINE": "online.com",
    "PEUGEOT": "peugeot-motocycles.fr",
    "PIAGGIO": "piaggio.com",
    "POLARIS": "polaris.com",
    "PONY": "pony-motors.com",
    "PUCH": "puch.com",
    "QUADRO": "quadrovehicles.com",
    "RAY": "ray.com",
    "REWACO": "rewaco.com",
    "RGNT": "rgnt-motorcycles.com",
    "RIEJU": "rieju.com",
    "ROYAL ENFIELD": "royalenfield.com",
    "SACHS": "sachs.com",
    "SAKURA": "sakura.com",
    "SEGWAY": "segway.com",
    "SHERCO": "sherco.com",
    "SILENCE": "silence.com",
    "SKIDOO": "skidoo.com",
    "SKYTEAM": "skyteam.com",
    "SMC (SM)": "smcmotor.com",
    "SOLEX": "solex.com",
    "Stark": "starkfuture.com",
    "SUNRA": "sunraev.com",
    "SUPER SOCO": "supersoco.com",
    "SUR-RON": "sur-ron.com",
    "SUTER": "suter.com",
    "SUZUKI": "suzuki.com",
    "SWM": "swm-motorcycles.com",
    "SYM": "sym-global.com",
    "TALARIA": "talariamotor.com",
    "TARO": "taromoto.com",
    "TERROT": "terrot.com",
    "TGB": "tgb.com.tw",
    "TISTO": "tisto.com",
    "TM": "tm-racing.com",
    "TOMOS": "tomos.com",
    "TORROT": "torrot.com",
    "TRIUMPH": "triumphmotorcycles.com",
    "TRMOTOR": "trmotor.com",
    "UGBEST": "ugbest.com",
    "URAL": "imz-ural.com",
    "VANDERHALL": "vanderhallusa.com",
    "VECTRIX": "vectrix.com",
    "VELOCETTE": "velocette.com",
    "VENT": "ventmoto.com",
    "VICTORY": "victorymotorcycles.com",
    "VMOTO": "vmoto.com",
    "VOGE": "voge-motor.com",
    "WALZ": "walz.com",
    "WALZWERK": "walzwerk.com",
    "WOTTAN": "wottanmotor.com",
    "YAMAHA": "yamaha-motor.com",
    "ZERO": "zeromotorcycles.com",
    "ZERO ENGINEERING": "zero-eng.com",
    "ZONTES": "zontes.com",
    "ZÜNDAPP": "zuendapp.com"
}

# Créez le dossier 'logos' s'il n'existe pas
if not os.path.exists('logos'):
    os.makedirs('logos')

# Téléchargement des logos
for brand, site in brands_sites.items():
    try:
        response = requests.get(f"https://img.logo.dev/{site}?token=pk_cQ0rwgtPQfevHiVBURyOGg")
        if response.status_code == 200:
            img = Image.open(BytesIO(response.content))
            img.save(f'logos/{brand}.jpeg')
        else:
            print(f"Logo not found for {brand}")
    except Exception as e:
        print(f"Could not download logo for {brand}: {e}")
