<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMNnWSX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMNnWSX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMNnWSX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMNnWSX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNMNnWSX\App_KernelDevDebugContainer([
    'container.build_hash' => 'NMNnWSX',
    'container.build_id' => '1c03b382',
    'container.build_time' => 1717802141,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMNnWSX');
