<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produits extends \App\Entity\Produits implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'produitCaract' => [parent::class, 'produitCaract', null],
        "\0".parent::class."\0".'produitDesc' => [parent::class, 'produitDesc', null],
        "\0".parent::class."\0".'produitName' => [parent::class, 'produitName', null],
        "\0".parent::class."\0".'produitPicture' => [parent::class, 'produitPicture', null],
        "\0".parent::class."\0".'produitPrice' => [parent::class, 'produitPrice', null],
        "\0".parent::class."\0".'produit_relation' => [parent::class, 'produit_relation', null],
        'id' => [parent::class, 'id', null],
        'produitCaract' => [parent::class, 'produitCaract', null],
        'produitDesc' => [parent::class, 'produitDesc', null],
        'produitName' => [parent::class, 'produitName', null],
        'produitPicture' => [parent::class, 'produitPicture', null],
        'produitPrice' => [parent::class, 'produitPrice', null],
        'produit_relation' => [parent::class, 'produit_relation', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
